### ISSUE TITLE
Argument 1 passed to Embed\Providers\Html::extractImages() must be an instance of DOMElement, null given

### ISSUE THREAD

**Issue by orottier** [oscarotero/Embed#58]
Catchable fatal error: Argument 1 passed to Embed\Providers\Html::extractImages() must be an instance of DOMElement, null given, called in /var/www/vhosts/oscarotero.com/httpdocs/embed2/src/Providers/Html.php on line 33 and defined in /var/www/vhosts/oscarotero.com/httpdocs/embed2/src/Providers/Html.php on line 237

for example: 

http://oscarotero.com/embed2/demo/index.php?url=http%3A%2F%2Fblogs.wsj.com%2Fdigits%2F2015%2F05%2F08%2Famazons-prices-often-undercut-by-upstart-jet-com-study-finds%2F

Probably has to do with the WSJ paywall?

**Comment by oscarotero** [comment]
I see this is because [this function](https://github.com/oscarotero/Embed/blob/a30a75896e2a8e2a2f81d12a750cfcbe7a0ab3fe/src/Providers/Html.php#L313) returns null, because the PHP's DOMDocument library cannot find the `<body>` element (but this element exists in the html, maybe the code is malformed). I've fixed it returning the `<html>` element if `<body>` wasn't found.

**Comment by rohitkhatri** [comment]
It still throws FatalThrowableError which I can't catch in laravel 5.1

**Comment by oscarotero** [comment]
It seems a problem with the DOMDocument library that cannot parse the html correctly. I'm going to fix this to not throw the execption, but I have to investigate why this html code cannot be parsed.

**Comment by rohitkhatri** [comment]
@oscarotero thanks.. :-)
